-- Generated by the validation rule script
-- Review before executing against your database

INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1166, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1172, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1173, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1171, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1191, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1183, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1188, 'validate_ssn_nist');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1189, 'validate_ssn_nist');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1190, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1192, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1193, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1194, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1197, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1195, 'validate_ssn_nist');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1196, 'validate_ssn_nist');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1198, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1204, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1201, 'validate_luhn_algorithm');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1205, 'validate_ssn_nist');
INSERT INTO classifier_validation_rules (classifier_id, validation_fn_name) VALUES (1202, 'validate_luhn_algorithm');
